name: Build and push docker
on: [push]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - npm run install
      - npm run test
  build-and-push-docker:
    name: Build and Push docker
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: mr-smithers-excellent/docker-build-push@v4
          with:
                image: ryanroundhouse/liar-server
                registry: docker.io
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}