on: [push]
uses: mr-smithers-excellent/docker-build-push@v4
with:
  image: ryanroundhouse/liar
  registry: docker.io
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}