name: Build and push docker
on: [push]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    env:
      server-directory: './server'
      interface-directory: './liars-dice-interface'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
        working-directory: ${{env.interface-directory}}
      - run: npm run build
        working-directory: ${{env.interface-directory}}
      - run: npm i
        working-directory: ${{env.server-directory}}
      - run: npm run test
        working-directory: ${{env.server-directory}}
  build-and-push-docker:
    name: Build and Push docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      server-directory: './server'
      interface-directory: './liars-dice-interface'
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: get interface_node_modules
        run: npm i
        working-directory: ${{env.interface-directory}}
      - name: building interface
        run: npm run build
        working-directory: ${{env.interface-directory}}
      - name: get server_node_modules
        run: npm i
        working-directory: ${{env.server-directory}}
      - name: building server
        run: npm run build
        working-directory: ${{env.server-directory}}
      - name: build and push dockerimage
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ryanroundhouse/liar-server
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        working-directory: ${{env.server-directory}}